import { ConfigPlugin, withPodfile } from "expo/config-plugins"

const PODFILE_MARKER = "# @generated by withIosDeploymentTarget"

/**
 * CocoaPods preserves deployment targets declared by individual podspecs.
 * Xcode 27 rejects targets below iOS 15, even when the application itself
 * has a newer deployment target, so raise every generated Pods target to the
 * application's minimum version.
 */
export const withIosDeploymentTarget: ConfigPlugin<{ deploymentTarget: string }> = (
  config,
  { deploymentTarget },
) =>
  withPodfile(config, (podfileConfig) => {
    if (podfileConfig.modResults.contents.includes(PODFILE_MARKER)) return podfileConfig

    const postInstall = "  post_install do |installer|"
    if (!podfileConfig.modResults.contents.includes(postInstall)) {
      throw new Error("Could not find the CocoaPods post_install hook")
    }

    const deploymentTargetOverride = `${postInstall}
    ${PODFILE_MARKER}
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        current_target = build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        if current_target.nil? || Gem::Version.new(current_target) < Gem::Version.new('${deploymentTarget}')
          build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '${deploymentTarget}'
        end
      end
    end`

    podfileConfig.modResults.contents = podfileConfig.modResults.contents.replace(
      postInstall,
      deploymentTargetOverride,
    )

    return podfileConfig
  })
