// Regenerates the old-build outbox code the rollback and forward scenarios load.
// Usage: node src/features/sync/stress/legacy/fetch.mjs [ref=dir ...]
// Defaults: origin/main=main v0.1.1=v0_1_1
import { execFileSync } from "node:child_process"
import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join, posix, relative } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, "../../../../..")

// why: only the code that parses, writes, and sends outbox records is pinned to the old ref; everything else is today's code.
const pinned = {
  "src/features/sync/durableOutbox.ts": "durableOutbox",
  "src/features/sync/drainOutbox.ts": "drainOutbox",
  "src/features/sync/outboxController.ts": "outboxController",
  "src/features/sync/snapshotStore.ts": "snapshotStore",
  "src/features/connected/persistence.ts": "persistence",
  "src/features/decks/decksSyncWrites.ts": "decksSyncWrites",
  "src/features/decks/decksVersionWrites.ts": "decksVersionWrites",
}

const refs = process.argv.length > 2
  ? process.argv.slice(2).map((pair) => pair.split("="))
  : [["origin/main", "main"], ["v0.1.1", "v0_1_1"]]

const git = (...args) => execFileSync("git", args, { cwd: repo, encoding: "utf8" })

function resolveSpecifier(fromFile, specifier) {
  if (specifier.startsWith("@/")) return `src/${specifier.slice(2)}`
  if (specifier.startsWith(".")) return posix.normalize(posix.join(posix.dirname(fromFile), specifier))
  return null
}

for (const [ref, directory] of refs) {
  const sha = git("rev-parse", ref).trim()
  const outDirectory = join(here, directory)
  mkdirSync(outDirectory, { recursive: true })
  for (const [path, name] of Object.entries(pinned)) {
    const source = git("show", `${ref}:${path}`)
    const rewritten = source.replace(/(from\s+|import\s+)"([^"]+)"/g, (match, lead, specifier) => {
      const target = resolveSpecifier(path, specifier)
      if (!target) return match
      const pinnedName = pinned[`${target}.ts`]
      if (pinnedName) return `${lead}"./${pinnedName}"`
      if (target.startsWith("src/")) return `${lead}"@/${target.slice(4)}"`
      const fromHere = relative(outDirectory, join(repo, target)).split("\\").join("/")
      return `${lead}"${fromHere}"`
    })
    const header = `/* eslint-disable */\n// Generated by legacy/fetch.mjs from ${ref} (${sha.slice(0, 8)}):${path}. Do not edit.\n`
    writeFileSync(join(outDirectory, `${name}.ts`), header + rewritten)
  }
  console.log(`${ref} -> ${directory} (${sha.slice(0, 8)})`)
}
